# Welcome to Jekyll!
#

# Site settings
title: Paul Bryan
description: Front End Web Developer
owner: Paul Bryan
first_published: 2016 # if migrating another site, the year of your first publish
email: info@paulbryan.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paulbryan.io" # the base hostname & protocol for your site
social:
  email:             info@paulbryan.io
  github:            https://github.com/paulbryan-dev
  linkedin-square:   https://uk.linkedin.com/in/paulbryan-dev
  twitter:           https://twitter.com/paulbryan_dev
  facebook-official: https://www.facebook.com/paul.bryan.503
  Codewars:          https://www.codewars.com/users/PaulBryan_dev/badges/large

  #google-plus-square: https://plus.google.com/u/0/+<username>
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
